# Generated by Django 4.1.4 on 2022-12-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=50)),
                ('service_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datopago.paymentuser')),
            ],
        ),
        migrations.AddField(
            model_name='paymentuser',
            name='userx_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datopago.userx'),
        ),
        migrations.CreateModel(
            name='ExpiredPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_fee_amount', models.FloatField(default=0.0)),
                ('payment_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datopago.paymentuser')),
            ],
        ),
    ]
